// Code generated by github.com/hidori/go-genprop/cmd/genprop DO NOT EDIT.
package basic

func (t *User) GetID() int {
	return t.id
}
func (t *User) GetName() string {
	return t.name
}
func (t *User) SetName(v string) {
	t.name = v
}
func (t *User) GetEmail() string {
	return t.email
}
func (t *User) SetEmail(v string) {
	t.email = v
}
func (t *User) setPassword(v string) {
	t.password = v
}
