// Code generated by github.com/hidori/go-genprop/cmd/genprop DO NOT EDIT.
package example

func (t *Struct) GetValue1() int {
	return t.value1
}
func (t *Struct) SetValue2(v int) {
	t.value2 = v
}
func (t *Struct) GetValue3() int {
	return t.value3
}
func (t *Struct) SetValue3(v int) {
	t.value3 = v
}
func (t *Struct) setValue4(v int) {
	t.value4 = v
}
func (t *Struct) GetValue5() int {
	return t.value5
}
func (t *Struct) SetValue5(v int) error {
	err := validateFieldValue(v, "min=1,max=100")
	if err != nil {
		return err
	}
	t.value5 = v
	return nil
}
func (t *Struct) GetValue6() int {
	return t.value6
}
func (t *Struct) setValue6(v int) error {
	err := validateFieldValue(v, "min=1,max=100")
	if err != nil {
		return err
	}
	t.value6 = v
	return nil
}
