// Code generated by github.com/hidori/go-genprop/cmd/genprop DO NOT EDIT.
package example

func (t *ExampleStruct) GetValue1() int {
	return t.value1
}
func (t *ExampleStruct) SetValue2(v int) {
	t.value2 = v
}
func (t *ExampleStruct) GetValue3() int {
	return t.value3
}
func (t *ExampleStruct) SetValue3(v int) {
	t.value3 = v
}
func (t *ExampleStruct) GetID() int {
	return t.id
}
func (t *ExampleStruct) GetAPI() string {
	return t.api
}
func (t *ExampleStruct) GetURL() string {
	return t.url
}
func (t *ExampleStruct) GetHttp() string {
	return t.http
}
