version: "2"

run:
  tests: false
  allow-parallel-runners: true

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - nlreturn
    - revive
    - wsl

formatters:
  exclusions:
    paths:
      - ".*\\_test\\.go$"
      - ".*\\_mock\\.go$"
      - ".*\\_prop\\.go$"
