version: "2"
run:
  tests: false
  allow-parallel-runners: true

linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - forbidigo
    - gochecknoglobals
    - revive
  settings:
    cyclop:
      max-complexity: 20
    gocyclo:
      min-complexity: 20

  exclusions:
    paths:
      - ".*example/.*\\.go$"

formatters:
  exclusions:
    paths:
      - ".*\\_test\\.go$"
      - ".*\\_mock\\.go$"
      - ".*\\_prop\\.go$"
