// Code generated by github.com/hidori/go-genprop/cmd/genprop DO NOT EDIT.
package example

import "net/http"

func (t *APIClient) GetClient() http.Client {
	return t.client
}
func (t *APIClient) setClient(v http.Client) {
	t.client = v
}
func (t *APIClient) GetURL() string {
	return t.url
}
func (t *APIClient) setURL(v string) {
	t.url = v
}
