// Code generated by github.com/hidori/go-genprop/cmd/genprop DO NOT EDIT.
package example

func NewAccount(id int, username string, email string, password string) (*Account, error) {
	s := &Account{}
	s.id = id
	err := s.SetUsername(username)
	if err != nil {
		return nil, err
	}
	err = s.SetEmail(email)
	if err != nil {
		return nil, err
	}
	err = s.setPassword(password)
	if err != nil {
		return nil, err
	}
	return s, nil
}
func (t *Account) GetID() int {
	return t.id
}
func (t *Account) GetUsername() string {
	return t.username
}
func (t *Account) SetUsername(v string) error {
	err := validateField("username", v, "required,min=3,max=20")
	if err != nil {
		return err
	}
	t.username = v
	return nil
}
func (t *Account) GetEmail() string {
	return t.email
}
func (t *Account) SetEmail(v string) error {
	err := validateField("email", v, "required,email")
	if err != nil {
		return err
	}
	t.email = v
	return nil
}
func (t *Account) setPassword(v string) error {
	err := validateField("password", v, "required,min=8,containsany=!@#$")
	if err != nil {
		return err
	}
	t.password = v
	return nil
}
