// Code generated by github.com/hidori/go-genprop/cmd/genprop DO NOT EDIT.
package example1

func (t *Person) GetID() int {
	return t.id
}
func (t *Person) GetName() string {
	return t.name
}
func (t *Person) SetName(v string) {
	t.name = v
}
func (t *Person) GetAge() int {
	return t.age
}
func (t *Person) SetAge(v int) {
	t.age = v
}
