package app

import (
	"bytes"
	"go/ast"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestParseFile(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name     string
		fileName string
		wantErr  bool
	}{
		{
			name:     "failure: non-existent file",
			fileName: "non_existent_file.go",
			wantErr:  true,
		},
		{
			name:     "success: calls internal parser",
			fileName: "../../testdata/internal/valid_syntax_input.go.txt",
			wantErr:  false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			file, err := parseFile(tt.fileName)

			if tt.wantErr {
				assert.Error(t, err)
				assert.Nil(t, file)
			} else {
				require.NoError(t, err)
				assert.NotNil(t, file)
			}
		})
	}
}

func TestGenerateCode(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		file    *ast.File
		wantErr bool
	}{
		{
			name: "success: calls internal generator",
			file: &ast.File{
				Name:  ast.NewIdent("test"),
				Decls: []ast.Decl{},
			},
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			decls, err := generateCode(tt.file, "id,url,api", "validateFieldValue", "validate")

			if tt.wantErr {
				assert.Error(t, err)
				assert.Nil(t, decls)
			} else {
				require.NoError(t, err)
			}
		})
	}
}

func TestWriteOutput(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name        string
		packageName string
		decls       []ast.Decl
		wantErr     bool
	}{
		{
			name:        "success: empty decls",
			packageName: "test",
			decls:       []ast.Decl{},
			wantErr:     false,
		},
		{
			name:        "success: valid decls",
			packageName: "test",
			decls: []ast.Decl{
				&ast.FuncDecl{
					Name: ast.NewIdent("TestFunc"),
					Type: &ast.FuncType{
						Params: &ast.FieldList{},
					},
					Body: &ast.BlockStmt{
						List: []ast.Stmt{},
					},
				},
			},
			wantErr: false,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var buffer bytes.Buffer
			err := writeOutput(&buffer, tt.packageName, tt.decls)

			if tt.wantErr {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
				output := buffer.String()
				assert.Contains(t, output, "// Code generated by")
				assert.Contains(t, output, "package "+tt.packageName)
			}
		})
	}
}

func TestGenerate(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name         string
		fileName     string
		wantErr      bool
		wantContains []string
	}{
		{
			name:     "success: generates code for valid file",
			fileName: filepath.Join("..", "..", "testdata", "internal", "valid_syntax_input.go.txt"),
			wantErr:  false,
			wantContains: []string{
				"// Code generated by",
				"package test",
				"func (t *TestStruct) GetField() string",
				"func (t *TestStruct) SetField(v string)",
			},
		},
		{
			name:     "failure: non-existent file",
			fileName: "non_existent_file.go",
			wantErr:  true,
		},
		{
			name:     "failure: invalid syntax file",
			fileName: filepath.Join("..", "..", "testdata", "internal", "invalid_syntax_input.go.txt"),
			wantErr:  true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			var buffer bytes.Buffer
			err := generate(&buffer, tt.fileName, "id,url,api", "validateFieldValue", "validate")

			if tt.wantErr {
				require.Error(t, err)
				return
			}

			require.NoError(t, err)
			output := buffer.String()

			for _, want := range tt.wantContains {
				assert.Contains(t, output, want)
			}
		})
	}
}

func TestRun(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		args    []string
		wantErr bool
	}{
		{
			name:    "success: run with valid file argument",
			args:    []string{"genprop", filepath.Join("..", "..", "testdata", "internal", "valid_syntax_input.go.txt")},
			wantErr: false,
		},
		{
			name:    "failure: run with non-existent file",
			args:    []string{"genprop", "non_existent_file.go"},
			wantErr: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()

			err := RunWithArgs(tt.args[1:]) // Skip program name

			if tt.wantErr {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
			}
		})
	}
}
