// Code generated by github.com/hidori/go-genprop/cmd/genprop DO NOT EDIT.
package example

func NewUser(id int, name string, email string) *User {
	s := &User{}
	s.id = id
	s.SetName(name)
	s.SetEmail(email)
	return s
}
func (t *User) GetID() int {
	return t.id
}
func (t *User) GetName() string {
	return t.name
}
func (t *User) SetName(v string) {
	t.name = v
}
func (t *User) GetEmail() string {
	return t.email
}
func (t *User) SetEmail(v string) {
	t.email = v
}
