// Code generated by github.com/hidori/go-genprop/cmd/genprop DO NOT EDIT.
package example2

func (t *User) GetEmail() string {
	return t.email
}
func (t *User) SetEmail(v string) error {
	err := validateFieldValue("email", v, "email")
	if err != nil {
		return err
	}
	t.email = v
	return nil
}
func (t *User) setPassword(v string) error {
	err := validateFieldValue("password", v, "min=8")
	if err != nil {
		return err
	}
	t.password = v
	return nil
}
func (t *User) GetScore() int {
	return t.score
}
func (t *User) SetScore(v int) error {
	err := validateFieldValue("score", v, "min=0,max=100")
	if err != nil {
		return err
	}
	t.score = v
	return nil
}
