on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-go@v6
      with:
        go-version: '1.24'
    - uses: golangci/golangci-lint-action@v8
      with:
        version: latest
        args: ./internal/... ./public/...
    - run: make test
    - run: make example/run
    - run: make container/build
